name: KB Pro IPTV Bot

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python generate_m3u.py
        env:
          BOT_NAME: ${{ secrets.BOT_NAME }}
          BASE_API: ${{ secrets.BASE_API }}

      - name: Commit file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ROARZONET.m3u8
          git commit -m "auto update" || echo "no change"
          git push
